//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSO2_Scratch_Parser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSO2_Scratch_Parser.Culture.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO2NGS Scratch Parser.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Item Names.
        /// </summary>
        public static string BonusItemName {
            get {
                return ResourceManager.GetString("BonusItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Scratch.
        /// </summary>
        public static string ClearScratch {
            get {
                return ResourceManager.GetString("ClearScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Items.
        /// </summary>
        public static string DownloadAllImages {
            get {
                return ResourceManager.GetString("DownloadAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Items Only.
        /// </summary>
        public static string DownloadBonusImage {
            get {
                return ResourceManager.GetString("DownloadBonusImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus List.
        /// </summary>
        public static string DownloadBonusListJson {
            get {
                return ResourceManager.GetString("DownloadBonusListJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Images.
        /// </summary>
        public static string DownloadImageLabel {
            get {
                return ResourceManager.GetString("DownloadImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Items Only.
        /// </summary>
        public static string DownloadItemImage {
            get {
                return ResourceManager.GetString("DownloadItemImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string DownloadItemListJson {
            get {
                return ResourceManager.GetString("DownloadItemListJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download JSON.
        /// </summary>
        public static string DownloadJSONLabel {
            get {
                return ResourceManager.GetString("DownloadJSONLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string FetchScratch {
            get {
                return ResourceManager.GetString("FetchScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string LabelCultureName {
            get {
                return ResourceManager.GetString("LabelCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Names.
        /// </summary>
        public static string MainItemName {
            get {
                return ResourceManager.GetString("MainItemName", resourceCulture);
            }
        }
    }
}
